version: "3.7"

x-refs:
  restart-3s: &restart-3s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
  pip-data:
    driver: local
  yarn-data:
    driver: local

configs:
  noiseblend-v0.toml:
    file: ./noiseblend/production.toml
  spfy-v0.toml:
    file: ./spfy/production.toml
  redis-v0.conf:
    file: ./redis/redis.conf
  noiseblend-v6.com:
    file: ./nginx/noiseblend.com
  lunar-v2.fyi:
    file: ./nginx/lunar.fyi
  alinpanaitiu-v1.com:
    file: ./nginx/alinpanaitiu.com
  cloudflare-v0:
    file: ./nginx/cloudflare
  nginx-v4.conf:
    file: ./nginx/nginx.conf
  proxy_params-v1:
    file: ./nginx/proxy_params
  ssl_params-v1:
    file: ./nginx/ssl_params
  lunar_ssl_params-v1:
    file: ./nginx/lunar_ssl_params
  alinpanaitiu_ssl_params-v0:
    file: ./nginx/alinpanaitiu_ssl_params
  cors_headers-v2:
    file: ./nginx/cors_headers
  staging_cors_headers-v2:
    file: ./nginx/staging_cors_headers

secrets:
  htpasswd-v0:
    file: ./secrets/htpasswd
  redis_password-v0:
    file: ./secrets/redis_password
  redis_url-v0:
    file: ./secrets/redis_url
  spotify_client_id-v0:
    file: ./secrets/spotify_client_id
  spotify_client_secret-v0:
    file: ./secrets/spotify_client_secret
  unsplash_client_id-v0:
    file: ./secrets/unsplash_client_id
  unsplash_client_secret-v0:
    file: ./secrets/unsplash_client_secret
  sendgrid_api_key-v0:
    file: ./secrets/sendgrid_api_key
  postgres_password-v0:
    file: ./secrets/postgres_password
  alexa_secret-v0:
    file: ./secrets/alexa_secret
  noiseblend-v0.cert.pem:
    file: ./secrets/noiseblend.cert.pem
  noiseblend-v0.key.pem:
    file: ./secrets/noiseblend.key.pem
  lunar-v0.cert.pem:
    file: ./secrets/lunar.cert.pem
  lunar-v0.key.pem:
    file: ./secrets/lunar.key.pem
  alinpanaitiu-v0.cert.pem:
    file: ./secrets/alinpanaitiu.cert.pem
  alinpanaitiu-v0.key.pem:
    file: ./secrets/alinpanaitiu.key.pem
  cloudflare-v2.crt:
    file: ./secrets/cloudflare.crt
  sentry_dsn_api-v0:
    file: ./secrets/sentry_dsn_api
  sentry_dsn_frontend-v0:
    file: ./secrets/sentry_dsn_frontend

networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay
  postgres:
    driver: overlay
  redis:
    driver: overlay
  nginx:
    driver: overlay

services:
  api:
    <<: *restart-3s
    build:
      context: $NOISEBLEND_API_DIR
      dockerfile: Dockerfile
    configs:
      - source: noiseblend-v0.toml
        target: /root/.config/noiseblend/develop.toml
      - source: spfy-v0.toml
        target: /root/.config/spfy/develop.toml
    image: noiseblend/api:latest
    environment:
      SPFY_APP_CLIENT_ID__FILE: /run/secrets/spotify_client_id-v0
      SPFY_APP_CLIENT_SECRET__FILE: /run/secrets/spotify_client_secret-v0
      SPFY_UNSPLASH_AUTH_CLIENT_ID__FILE: /run/secrets/unsplash_client_id-v0
      SPFY_UNSPLASH_AUTH_CLIENT_SECRET__FILE: /run/secrets/unsplash_client_id-v0
      SPFY_REDIS_URL__FILE: /run/secrets/redis_url-v0
      SPFY_REDIS_PASSWORD__FILE: /run/secrets/redis_password-v0
      SPFY_DATABASE_CONNECTION_PASSWORD__FILE: /run/secrets/postgres_password-v0

      NOISEBLEND_SPOTIFY_CLIENT_ID__FILE: /run/secrets/spotify_client_id-v0
      NOISEBLEND_SPOTIFY_CLIENT_SECRET__FILE: /run/secrets/spotify_client_secret-v0
      NOISEBLEND_DB_CONNECTION_PASSWORD__FILE: /run/secrets/postgres_password-v0
      NOISEBLEND_SENDGRID_APIKEY__FILE: /run/secrets/sendgrid_api_key-v0
      NOISEBLEND_REDIS_AUTH_PASSWORD__FILE: /run/secrets/redis_password-v0
      NOISEBLEND_ALEXA_CLIENT_SECRET__FILE: /run/secrets/alexa_secret-v0
      NOISEBLEND_SENTRY_DSN__FILE: /run/secrets/sentry_dsn_api-v0
    depends_on:
      - redis
      - postgres
    networks:
      - backend
      - redis
      - postgres
      - nginx
    ports:
      - "9003:9000"
    secrets:
      - redis_password-v0
      - redis_url-v0
      - spotify_client_id-v0
      - spotify_client_secret-v0
      - unsplash_client_id-v0
      - unsplash_client_secret-v0
      - sendgrid_api_key-v0
      - postgres_password-v0
      - alexa_secret-v0
      - sentry_dsn_api-v0
    volumes:
      - pip-data:/cache

  postgres:
    <<: *restart-3s
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password-v0
    image: postgres:11
    networks:
      - postgres
    ports:
      - "5434:5432"
    secrets:
      - postgres_password-v0
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/init.d:/docker-entrypoint-initdb.d:ro

  frontend:
    <<: *restart-3s
    build:
      context: $NOISEBLEND_UI_DIR
      dockerfile: Dockerfile
      args:
        - SENTRY_DSN=https://7a3ddfbacc0c4e2d98f105aa0f184e0b@sentry.io/1209883
        - SENTRY_AUTH_TOKEN
        - SENTRY_RELEASE
        - LOCAL_API_URL=http://api:9000/
        - REMOTE_API_URL=https://api.noiseblend.com/
        - LOCAL_WS_URL=ws://api:9000
        - REMOTE_WS_URL=wss://api.noiseblend.com
        - DOMAIN=www.noiseblend.com
    depends_on:
      - api
    image: noiseblend/ui:latest
    environment:
      NODE_ENV: production
    networks:
      - frontend
      - backend
      - nginx
    ports:
      - "3003:3000"
    volumes:
      - yarn-data:/cache

  redis:
    <<: *restart-3s
    command:
      - /bin/sh
      - -c
      - cat /etc/redis.conf | sed "s/# requirepass \"\"/requirepass \"$$( cat /run/secrets/redis_password-v0 )\"/g" | redis-server -
    configs:
      - source: redis-v0.conf
        target: /etc/redis.conf
    image: redis:alpine
    networks:
      - redis
    ports:
      - "6383:6379"
    secrets:
      - redis_password-v0
    volumes:
      - redis-data:/data

  nginx:
    <<: *restart-3s
    configs:
      - source: nginx-v4.conf
        target: /usr/local/openresty/nginx/conf/nginx.conf
      - source: cloudflare-v0
        target: /etc/nginx/conf.d/cloudflare.conf
      - source: proxy_params-v1
        target: /etc/nginx/proxy_params
      - source: ssl_params-v1
        target: /etc/nginx/ssl_params
      - source: lunar_ssl_params-v1
        target: /etc/nginx/lunar_ssl_params
      - source: alinpanaitiu_ssl_params-v0
        target: /etc/nginx/alinpanaitiu_ssl_params
      - source: cors_headers-v2
        target: /etc/nginx/cors_headers
      - source: staging_cors_headers-v2
        target: /etc/nginx/staging_cors_headers
      - source: noiseblend-v6.com
        target: /etc/nginx/conf.d/noiseblend.com.conf
      - source: lunar-v2.fyi
        target: /etc/nginx/conf.d/lunar.fyi.conf
      - source: alinpanaitiu-v1.com
        target: /etc/nginx/conf.d/alinpanaitiu.com.conf
    image: openresty/openresty:bionic
    networks:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - noiseblend-v0.cert.pem
      - noiseblend-v0.key.pem
      - lunar-v0.cert.pem
      - lunar-v0.key.pem
      - alinpanaitiu-v0.cert.pem
      - alinpanaitiu-v0.key.pem
      - cloudflare-v2.crt
      - htpasswd-v0
    volumes:
      - $NOISEBLEND_UI_DIR/static:/static/Noiseblend
      - /static/Lunar:/static/Lunar
      - /static/alinpanaitiu:/static/alinpanaitiu
      - /var/log/lunar-analytics:/var/log/lunar-analytics
