version: "3.7"

x-refs:
  restart-3s: &restart-3s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s

volumes:
  swarmpit-data:
    driver: local
  couchdb-data:
    driver: local

networks:
  swarmpit:
    driver: overlay
  nginx:
    external: true
    name: noiseblend_nginx

services:
  couchdb:
    <<: *restart-3s
    image: klaemo/couchdb:2.0.0
    networks:
      - swarmpit
    ports:
      - "5986:5984"
    volumes:
      - couchdb-data:/opt/couchdb/data

  swarmpit:
    <<: *restart-3s
    environment:
      SWARMPIT_DB: http://couchdb:5984
      SWARMPIT_WORKDIR: /var/lib/swarmpit
    image: swarmpit/swarmpit:latest
    networks:
      - swarmpit
      - nginx
    ports:
      - "888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - swarmpit-data:/var/lib/swarmpit

  swarmpit-agent:
    environment:
      DOCKER_API_VERSION: "1.40"
    image: swarmpit/agent:latest
    networks:
      - swarmpit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
