[app]
client_id = ""
client_secret = ""
redirect_uri = "http://localhost:3003"

[http]
connections = 30
concurrent_connections = 200
parallel_connections = 20
retries = 3

[database]
generate_mapping = false
acquire_timeout = 1.0

[email]
host = "smtp.gmail.com"
port = 587
use_tls = true
usr = ""
pwd = ""

[auth]
flow = "authorization_code"
send_auth_url_to_email = false
email = ""
username = ""

[player]
device = ""
speaker = ""

[unsplash]
app_name = "Noiseblend"

[redis]
host = "redis"
port = 6379
password = ""

url = ""
minsize = 1
maxsize = 10

[cache]
expire = 432000
encoding = "UTF-8"

[database.connection]
provider = "postgres"
user = "postgres"
password = ""
host = "postgres"
database = "postgres"

[auth.callback]
enabled = false
port = ""
timeout = 30

[player.alsa]
device = "default"
mixer = "PCM"

[unsplash.auth]
client_id = ""
client_secret = ""
redirect_uri = "urn:ietf:wg:oauth:2.0:oob"

[cache.key]
etag = "ETAG"
response = "RESPONSE"

[volume.fade.up]
limit = 70
start = 1
step = 1
seconds = 500

[volume.fade.down]
limit = 0
start = 70
step = -1
seconds = 1000
