[spotify]
client_id = ""
client_secret = ""
redirect_uri = "https://staging.noiseblend.com"
scope = [
    "user-read-email",
    "user-read-private",
    "user-read-birthdate",
    "user-library-read",
    "user-library-modify",
    "user-top-read",
    "user-modify-playback-state",
    "user-read-playback-state",
    "user-read-currently-playing",
    "user-read-recently-played",
    "playlist-read-private",
    "playlist-read-collaborative",
    "playlist-modify-public",
    "playlist-modify-private",
    "ugc-image-upload"
]

[api]
cors = false
allow_origins = [
    "https://staging.noiseblend.com",
    "https://staging.noiseblend.com:3000"
]

[db]
create_tables = true

[db.connection]
user = "postgres"
password = ""
host = "postgres"
database = "postgres"
port = 5432

[db.pool]
min_size = 2
max_size = 20
max_inactive_connection_lifetime = 300.0

[sendgrid]
template_id = "fa61a7d0-2182-46d6-97be-49871f2950cb"
apikey = ""
sender = "confirm@noiseblend.com"

[sentry]
dsn = ""
release = "production"
environment = "production"

[redis.pool]
minsize = 2
maxsize = 20
[redis.auth]
host = "redis"
port = 6379
password = ""

[alexa]
auth_type = "basic"
client_id = "alexa-blend"
client_secret = ""
